# Generated by Django 5.1.3 on 2024-11-20 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProposalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road_name', models.CharField(max_length=200)),
                ('sanctioned_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('road_length', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sanctioned_date', models.DateField()),
                ('proposal_type', models.CharField(max_length=200)),
                ('proposal_sub_type', models.CharField(max_length=200)),
                ('estimated_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('verified_by_revenue_dept', models.BooleanField()),
                ('reference_letter', models.FileField(upload_to='pdfs/')),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_detail', to='proposals.proposal')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierAnualTurnover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_fy', models.CharField(max_length=10)),
                ('first_fy_to', models.DecimalField(decimal_places=2, max_digits=10)),
                ('first_fy_doc', models.FileField(upload_to='pdfs/')),
                ('second_fy', models.CharField(max_length=10)),
                ('second_fy_to', models.DecimalField(decimal_places=2, max_digits=10)),
                ('second_fy_doc', models.FileField(upload_to='pdfs/')),
                ('third_fy', models.CharField(max_length=10)),
                ('third_fy_to', models.DecimalField(decimal_places=2, max_digits=10)),
                ('third_fy_doc', models.FileField(upload_to='pdfs/')),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_annual_to', to='proposals.proposal')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierBankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=200)),
                ('bank_code', models.CharField(max_length=200)),
                ('ifsc_code', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=200)),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_bank_detail', to='proposals.proposal')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierBasicDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('pincode', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=200)),
                ('mob', models.CharField(max_length=200)),
                ('tele_fax', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('web_addr', models.CharField(max_length=200)),
                ('public_ltd', models.BooleanField()),
                ('partnership', models.BooleanField()),
                ('supplier_type', models.CharField(choices=[('Store & spares supplier', 'Store & spares supplier'), ('Auto spare supplier', 'Auto spare supplier'), ('TPP Spare supplier', 'TPP Sparesupplier'), ('Capital supplier', 'Capital supplier'), ('Contracts', 'Contracts'), ('Service Provider', 'Service Provider'), ('Related Party', 'Related Party'), ('Transporter', 'Transporter'), ('Raw Material Supplier', 'Raw Material Supplier'), ('Coal Supplier', 'Coal Supplier'), ('Packing material Supplier', 'Packing material Supplier'), ('Advertisement', 'Advertisement'), ('Rent', 'Rent'), ('Professional', 'Professional'), ('Any Other..', 'Any Other..')], max_length=200)),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_basic_detail', to='proposals.proposal')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('branch_office', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('pincode', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=200)),
                ('mob', models.CharField(max_length=200)),
                ('tele_fax', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_contact_info', to='proposals.proposal')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst_cert', models.FileField(upload_to='pdfs/')),
                ('pancard', models.FileField(upload_to='pdfs/')),
                ('cert_of_incorporation', models.FileField(upload_to='pdfs/')),
                ('msme_cert', models.FileField(upload_to='pdfs/')),
                ('director_aadharcard', models.FileField(upload_to='pdfs/')),
                ('director_pancard', models.FileField(upload_to='pdfs/')),
                ('cancelled_check', models.FileField(upload_to='pdfs/')),
                ('neft_form', models.FileField(upload_to='pdfs/')),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_docs', to='proposals.proposal')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierRegDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_number', models.CharField(max_length=200)),
                ('gst_number', models.CharField(max_length=200)),
                ('tax_exemption', models.CharField(max_length=200)),
                ('small_scale_reg', models.CharField(max_length=200)),
                ('type_of_msme', models.CharField(max_length=200)),
                ('msme_number', models.CharField(max_length=200)),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_reg_detail', to='proposals.proposal')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierTaxDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst_applicable', models.BooleanField()),
                ('tds_applicable', models.BooleanField()),
                ('tcs_applicable', models.BooleanField()),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_tax_detail', to='proposals.proposal')),
            ],
        ),
    ]
